# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.snikket;
  rootDomain = config.web.rootDomain;
  publicURL = "chat.${rootDomain}";
  environment = {
    "SNIKKET_ADMIN_EMAIL" = "admin@kafu.observer";
    "SNIKKET_DOMAIN" = publicURL;
    "SNIKKET_TWEAK_HTTPS_PORT" = "5443";
    "SNIKKET_TWEAK_HTTP_PORT" = "5080";
  };
in
{
  options.snikket = {
    enable = lib.mkEnableOption "snikket hosting";
  };

  config = lib.mkIf cfg.enable {
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."snikket" = {
      image = "snikket/snikket-server:stable";
      inherit environment;
      volumes = [
        "snikket_snikket_data:/snikket:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
      ];
    };
    systemd.services."podman-snikket" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-volume-snikket_snikket_data.service"
      ];
      requires = [
        "podman-volume-snikket_snikket_data.service"
      ];
      partOf = [
        "podman-compose-snikket-root.target"
      ];
      wantedBy = [
        "podman-compose-snikket-root.target"
      ];
    };
    virtualisation.oci-containers.containers."snikket-certs" = {
      image = "snikket/snikket-cert-manager:stable";
      inherit environment;
      volumes = [
        "snikket_acme_challenges:/var/www/.well-known/acme-challenge:rw"
        "snikket_snikket_data:/snikket:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
      ];
    };
    systemd.services."podman-snikket-certs" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-volume-snikket_acme_challenges.service"
        "podman-volume-snikket_snikket_data.service"
      ];
      requires = [
        "podman-volume-snikket_acme_challenges.service"
        "podman-volume-snikket_snikket_data.service"
      ];
      partOf = [
        "podman-compose-snikket-root.target"
      ];
      wantedBy = [
        "podman-compose-snikket-root.target"
      ];
    };
    virtualisation.oci-containers.containers."snikket-portal" = {
      image = "snikket/snikket-web-portal:stable";
      inherit environment;
      log-driver = "journald";
      extraOptions = [
        "--network=host"
      ];
    };
    systemd.services."podman-snikket-portal" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      partOf = [
        "podman-compose-snikket-root.target"
      ];
      wantedBy = [
        "podman-compose-snikket-root.target"
      ];
    };
    virtualisation.oci-containers.containers."snikket-proxy" = {
      image = "snikket/snikket-web-proxy:stable";
      inherit environment;
      volumes = [
        "snikket_acme_challenges:/var/www/html/.well-known/acme-challenge:rw"
        "snikket_snikket_data:/snikket:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
      ];
    };
    systemd.services."podman-snikket-proxy" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-volume-snikket_acme_challenges.service"
        "podman-volume-snikket_snikket_data.service"
      ];
      requires = [
        "podman-volume-snikket_acme_challenges.service"
        "podman-volume-snikket_snikket_data.service"
      ];
      partOf = [
        "podman-compose-snikket-root.target"
      ];
      wantedBy = [
        "podman-compose-snikket-root.target"
      ];
    };

    # Volumes
    systemd.services."podman-volume-snikket_acme_challenges" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect snikket_acme_challenges || podman volume create snikket_acme_challenges
      '';
      partOf = [ "podman-compose-snikket-root.target" ];
      wantedBy = [ "podman-compose-snikket-root.target" ];
    };
    systemd.services."podman-volume-snikket_snikket_data" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        podman volume inspect snikket_snikket_data || podman volume create snikket_snikket_data
      '';
      partOf = [ "podman-compose-snikket-root.target" ];
      wantedBy = [ "podman-compose-snikket-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-snikket-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    web.enable = lib.mkDefault true;

    # NGINX config
    services.nginx = {
      virtualHosts = {
        # -------------------------------------
        # HTTP Server Block
        # -------------------------------------
        "chat.${rootDomain}-http" = {
          serverName = "chat.${rootDomain}";
          serverAliases = [
            "groups.chat.${rootDomain}"
            "share.chat.${rootDomain}"
          ];

          listen = [
            {
              addr = "0.0.0.0";
              port = 80;
            }
            {
              addr = "[::]";
              port = 80;
            }
          ];

          locations."/" = {
            proxyPass = "http://localhost:5080/";
            extraConfig = ''
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

              # This is the maximum size of uploaded files in Snikket
              client_max_body_size 104857616; # 100MB + 16 bytes
            '';
          };
        };

        # -------------------------------------
        # HTTPS Server Block
        # -------------------------------------
        "chat.${rootDomain}-https" = {
          useACMEHost = rootDomain;
          forceSSL = true;

          serverName = "chat.${rootDomain}";
          serverAliases = [
            "groups.chat.${rootDomain}"
            "share.chat.${rootDomain}"
          ];

          listen = [
            {
              addr = "0.0.0.0";
              port = 443;
              ssl = true;
            }
            {
              addr = "[::]";
              port = 443;
              ssl = true;
              extraParameters = [ "ipv6only=on" ];
            }
          ];

          locations."/" = {
            proxyPass = "https://localhost:5443/";

            proxyWebsockets = true;

            extraConfig = ''
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

              # REMOVE THIS IF YOU CHANGE `localhost` TO ANYTHING ELSE ABOVE
              proxy_ssl_verify off;

              proxy_set_header X-Forwarded-Proto https;
              proxy_ssl_server_name on;

              # This is the maximum size of uploaded files in Snikket
              client_max_body_size 104857616; # 100MB + 16 bytes

              proxy_read_timeout 900s;
            '';
          };
        };
      };
    };

    #"${publicURL}" = {
    #  useACMEHost = rootDomain;
    #  forceSSL = true;
    #  locations."/".proxyPass = "http://127.0.0.1:5080";
    #};
    security.acme.certs."${rootDomain}".extraDomainNames = [
      publicURL
      "groups.${publicURL}"
      "share.${publicURL}"
    ];

    networking.firewall = {
      allowedTCPPorts = [
        5222
        5269
        5000
        3478
        3479
        5349
        5350
      ];
      allowedUDPPorts = [
        3478
        3479
        5349
        5350
      ];
      allowedUDPPortRanges = [
        {
          from = 49152;
          to = 65535;
        }
      ];
    };
  };
}
