systems = [
  "x86_64-linux",
  "aarch64-linux",
  "aarch64-darwin"
]

include = [
  "devShells.*.default",
  "devShells.*.deploy",
  "formatter.*",
  "checks.*",
  "nixosConfigurations.*",
  "darwinConfigurations.*",
]

exclude = [ ]

substituters = [
    "https://cache.kafu.observer",
    "https://nix-community.cachix.org", # nixvim
    "https://cache.nixos-cuda.org", # nvidia
    "https://ezkea.cachix.org" # aagl
]
trusted-public-keys = [
    "cache-kako-observer-1:Ly6DJShV3zBJlekZNqsY7EX+bJ1XXoIw/2CKXl14OIA=",

    "cache.ocf.berkeley.edu-1:6n9lihkjExzagz8GYR1QY/ZthT/XAKOy+ju5Jxd6wBg=",
    
    "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=",
    
    "cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M=",
    
    "ezkea.cachix.org-1:ioBmUbJTZIKsHmWWXPe1FSFbeVe+afhfgqgTSNd34eI="
]