name: Build and Cache

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  id-token: write

concurrency:
  group: build-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

jobs:
  Atelier:
    uses: stepbrobd/atelier/.github/workflows/discover.yaml@master
