name: Deploy

on:
  workflow_run:
    workflows: ["Build and Cache"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      method:
        description: "Method"
        required: true
        default: "switch"
        type: choice
        options:
        - switch
        - boot
        - test
      machines:
        description: "Machines"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  colmena-deploy:
    runs-on: ubuntu-latest
    environment: colmena-deploy
    steps:
      - uses: actions/checkout@v7

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:nix-ci

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Colmena apply
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "auto deploy..."
            nix develop -c colmena apply
          elif [ "${{ github.event.inputs.machines }}" == "" ]; then
            echo "manual deploy (all machines)..."
            nix develop -c colmena apply ${{ github.event.inputs.method }}
          else
            echo "manual deploy (specific machines)..."
            nix develop -c colmena apply --on ${{ github.event.inputs.machines }} ${{ github.event.inputs.method }}
          fi

