name: Nix Flake Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr-title: "nix flake update"
          pr-labels: |
            dependencies
            automated
          commit-msg: "nix flake update"
